/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
		'ril-emailril': '&#xe917;',
		'ril-sendril': '&#xe927;',
		'ril-align-justifyril': '&#xe901;',
		'ril-arrow-leftril': '&#xe928;',
		'ril-arrow-rightril': '&#xe92b;',
		'ril-chevron-leftril': '&#xe902;',
		'ril-chevron-rightril': '&#xe903;',
		'ril-chevrons-downril': '&#xe904;',
		'ril-chevrons-leftril': '&#xea02;',
		'ril-chevrons-rightril': '&#xea03;',
		'ril-chevrons-upril': '&#xe905;',
		'ril-eye1ril': '&#xe92e;',
		'ril-eye-offril': '&#xe92f;',
		'ril-github1ril': '&#xe930;',
		'ril-mailril': '&#xe931;',
		'ril-maximizeril': '&#xe906;',
		'ril-more-horizontalril': '&#xe907;',
		'ril-more-verticalril': '&#xe908;',
		'ril-moveril': '&#xe909;',
		'ril-navigation-2ril': '&#xe932;',
		'ril-sunril': '&#xe933;',
		'ril-user1ril': '&#xe935;',
		'ril-usersril': '&#xe936;',
		'ril-xril': '&#xe937;',
		'ril-linkril': '&#xe90a;',
		'ril-cameraril': '&#xe90b;',
		'ril-microphoneril': '&#xe90c;',
		'ril-checkmark1ril': '&#xe90d;',
		'ril-cancelril': '&#xe90e;',
		'ril-plusril': '&#xe90f;',
		'ril-cog1ril': '&#xe910;',
		'ril-cancel1ril': '&#xe911;',
		'ril-location1ril': '&#xe912;',
		'ril-trashcanril': '&#xe915;',
		'ril-smileyril': '&#xe913;',
		'ril-sadril': '&#xe914;',
		'ril-lockedril': '&#xe9c7;',
		'ril-unlockedril': '&#xe9c8;',
		'ril-magnifierril': '&#xe9c9;',
		'ril-gridril': '&#xe9cc;',
		'ril-listril': '&#xe9cd;',
		'ril-resizeril': '&#xe9d5;',
		'ril-resize1ril': '&#xe9d6;',
		'ril-enveloperil': '&#xe938;',
		'ril-heartril': '&#xe9d7;',
		'ril-moonril': '&#xe9dd;',
		'ril-popoutril': '&#xe9de;',
		'ril-popinril': '&#xe9df;',
		'ril-globeril': '&#xe9ff;',
		'ril-clipboardril': '&#xea00;',
		'ril-switchril': '&#xe916;',
		'ril-adoberil': '&#xe918;',
		'ril-adobeacrobatreaderril': '&#xe919;',
		'ril-adobeaftereffectsril': '&#xe91a;',
		'ril-adobeauditionril': '&#xe91b;',
		'ril-adobecreativecloudril': '&#xe91c;',
		'ril-adobedreamweaverril': '&#xe91d;',
		'ril-adobeillustratorril': '&#xe91e;',
		'ril-adobeindesignril': '&#xe91f;',
		'ril-adobelightroomccril': '&#xe920;',
		'ril-adobelightroomclassicril': '&#xe921;',
		'ril-adobephotoshopril': '&#xe922;',
		'ril-adobepremiereril': '&#xe923;',
		'ril-adobetypekitril': '&#xe924;',
		'ril-adobexdril': '&#xe925;',
		'ril-airbnbril': '&#xe926;',
		'ril-amazonril': '&#xe929;',
		'ril-amazonawsril': '&#xe92a;',
		'ril-androidril': '&#xe92c;',
		'ril-angularril': '&#xe92d;',
		'ril-behanceril': '&#xe934;',
		'ril-cplusplusril': '&#xe93a;',
		'ril-csharpril': '&#xe93c;',
		'ril-css3ril': '&#xe93d;',
		'ril-csswizardryril': '&#xe93e;',
		'ril-dot-netril': '&#xe943;',
		'ril-etsyril': '&#xe945;',
		'ril-evernoteril': '&#xe946;',
		'ril-facebookril': '&#xe947;',
		'ril-figmaril': '&#xe948;',
		'ril-gitril': '&#xe94b;',
		'ril-githubril': '&#xe94d;',
		'ril-gmailril': '&#xe94e;',
		'ril-goril': '&#xe94f;',
		'ril-googleril': '&#xe950;',
		'ril-googlechromeril': '&#xe952;',
		'ril-googledriveril': '&#xe954;',
		'ril-googlehangoutsril': '&#xe955;',
		'ril-googlepayril': '&#xe956;',
		'ril-googleplayril': '&#xe957;',
		'ril-gradleril': '&#xe958;',
		'ril-grouponril': '&#xe959;',
		'ril-html5ril': '&#xe95f;',
		'ril-internetexplorerril': '&#xe963;',
		'ril-iosril': '&#xe964;',
		'ril-itunesril': '&#xe965;',
		'ril-javaril': '&#xe966;',
		'ril-javascriptril': '&#xe967;',
		'ril-linuxril': '&#xe96a;',
		'ril-mail-dot-ruril': '&#xe96c;',
		'ril-megaril': '&#xe96f;',
		'ril-messengerril': '&#xe970;',
		'ril-microsoftril': '&#xe971;',
		'ril-mysqlril': '&#xe97e;',
		'ril-nextdoorril': '&#xe97f;',
		'ril-node-dot-jsril': '&#xe981;',
		'ril-phpril': '&#xe984;',
		'ril-pinterestril': '&#xe985;',
		'ril-postgresqlril': '&#xe989;',
		'ril-pythonril': '&#xe98a;',
		'ril-pyupril': '&#xe98b;',
		'ril-reactril': '&#xe98e;',
		'ril-sparkpostril': '&#xe996;',
		'ril-steemril': '&#xe99d;',
		'ril-steemitril': '&#xe99e;',
		'ril-steinbergril': '&#xe99f;',
		'ril-stencylril': '&#xe9a0;',
		'ril-stitcherril': '&#xe9a1;',
		'ril-stylusril': '&#xe9a4;',
		'ril-swaggerril': '&#xe9a5;',
		'ril-tailwindcssril': '&#xe939;',
		'ril-telegramril': '&#xe9a7;',
		'ril-teradataril': '&#xe9a8;',
		'ril-tiktokril': '&#xe9a9;',
		'ril-tripadvisorril': '&#xe9aa;',
		'ril-truliaril': '&#xe9ab;',
		'ril-tumblrril': '&#xe9ac;',
		'ril-twitchril': '&#xe9ad;',
		'ril-visaril': '&#xe9b5;',
		'ril-visualstudioril': '&#xe9b6;',
		'ril-visualstudiocoderil': '&#xe9b7;',
		'ril-vlcmediaplayerril': '&#xe9b8;',
		'ril-wazeril': '&#xe9b9;',
		'ril-whatsappril': '&#xe9ba;',
		'ril-wikipediaril': '&#xe9bb;',
		'ril-windowsril': '&#xe9bc;',
		'ril-wordpressril': '&#xe9be;',
		'ril-xboxril': '&#xe9bf;',
		'ril-xiaomiril': '&#xe9c0;',
		'ril-yahooril': '&#xe9c1;',
		'ril-youtuberil': '&#xe9c2;',
		'ril-comment-alt2-strokeril': '&#xe9c5;',
		'ril-comment-alt2-fillril': '&#xe9c6;',
		'ril-x-altx-altril': '&#xe9ca;',
		'ril-rssril': '&#xe9cb;',
		'ril-steering-wheelril': '&#xe9cf;',
		'ril-headphonesril': '&#xe9d0;',
		'ril-volumeril': '&#xe9d2;',
		'ril-volume-muteril': '&#xe9d3;',
		'ril-playril': '&#xe9d4;',
		'ril-battery-halfril': '&#xe9d8;',
		'ril-folder-fillril': '&#xe9d9;',
		'ril-bars-altril': '&#xe9db;',
		'ril-userril': '&#xe900;',
		'ril-map-pin-strokeril': '&#xe9e0;',
		'ril-homeril': '&#xe9e1;',
		'ril-home2ril': '&#xe9e2;',
		'ril-home3ril': '&#xe9e3;',
		'ril-pencilril': '&#xe9e4;',
		'ril-booksril': '&#xe9e5;',
		'ril-folder-openril': '&#xe9e6;',
		'ril-folder-plusril': '&#xe9e7;',
		'ril-phoneril': '&#xe9e8;',
		'ril-phone-hang-upril': '&#xe9e9;',
		'ril-address-bookril': '&#xe9ea;',
		'ril-envelopril': '&#xe9eb;',
		'ril-locationril': '&#xe9ec;',
		'ril-location2ril': '&#xe9ed;',
		'ril-alarmril': '&#xe9ee;',
		'ril-printerril': '&#xe9ef;',
		'ril-keyboardril': '&#xe9f0;',
		'ril-displayril': '&#xe9f1;',
		'ril-mobileril': '&#xe9f2;',
		'ril-tabletril': '&#xe9f3;',
		'ril-databaseril': '&#xe9f4;',
		'ril-bubbleril': '&#xe9f5;',
		'ril-bubbles2ril': '&#xe9f6;',
		'ril-spinner3ril': '&#xe9fa;',
		'ril-spinner6ril': '&#xe9fb;',
		'ril-searchril': '&#xe9fc;',
		'ril-zoom-inril': '&#xe9fd;',
		'ril-zoom-outril': '&#xe9fe;',
		'ril-cogril': '&#xea01;',
		'ril-eyeril': '&#xe9ce;',
		'ril-eye-blockedril': '&#xe9d1;',
		'ril-warningril': '&#xea07;',
		'ril-notificationril': '&#xea08;',
		'ril-checkmarkril': '&#xea10;',
		'ril-enterril': '&#xea13;',
		'ril-circle-rightril': '&#xea42;',
		'ril-circle-leftril': '&#xea44;',
		'ril-checkbox-uncheckedril': '&#xea53;',
		'ril-radio-uncheckedril': '&#xea56;',
		'ril-html-five2ril': '&#xeae5;',
		'ril-css31ril': '&#xeae6;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/ril-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
